### ISSUE TITLE
Code for the offline datasets generation

### ISSUE THREAD

**Issue by Howuhh** [jurgisp/dmc-memory-maze#14]
Hi! Very cool benchmark! Is it possible to publish the code with which the datasets were generated? I am very interested in testing my ideas about memory in Offline RL setup. However, for a complete benchmark (e.g. for a paper), I would like to have datasets for both 11x11 and 13x13 mazes too.

**Comment by jurgisp** [comment]
Hi, thanks for interest! Unfortunately the code to generate datasets is not available, but if you are working on a related research project, I would be happy to chat and give some tips. Just drop me an email (it's in the paper).
