### ISSUE TITLE
same colors for different maze sizes

### ISSUE THREAD

**Issue by Howuhh** [jurgisp/dmc-memory-maze#15]
Is there any way to make the number of colors the same for all sizes of mazes? I find it very interesting to test generalization on more complex problems by learning on easier ones. However, to test the memory only (and not a representations), it is important that the colors be familiar to the agent (for example during transition from 9x9 to 15x15 maze).

**Comment by jurgisp** [comment]
So 9x9 has 3 objects/colors and 15x15 has 6 objects/colors. Do you suggest that 9x9 would have 3 objects but sample randomly from all 6 available colors?

**Comment by Howuhh** [comment]
@jurgisp Yeah, something in such direction, so that the problem remains the same (well, I want to believe that the task will not change globally with such change and will not become more difficult), but there will be no representation shift after transfer to the new harder task. Maybe this can be an optional setting?

**Comment by jurgisp** [comment]
Yeah, I like the idea! It should be fairly easy to add such an option, I'll give it a go.

**Comment by jurgisp** [comment]
@Howuhh check out the PR and
```
python gui/run_gui.py --env "memory_maze:MemoryMaze-9x9-6CL-v0"
```
from the branch.

**Comment by Howuhh** [comment]
@jurgisp It's awesome, thanks! Seems to work nicely.
