### ISSUE TITLE
what about this longshort memory

### ISSUE THREAD

**Issue by zdx3578** [jurgisp/dmc-memory-maze#18]
https://github.com/NeuromorphicComputing/STPN

<img width="1116" alt="image" src="https://github.com/jurgisp/memory-maze/assets/382863/bb9b818d-2f8d-4c3f-a755-83010e3b5507">

<img width="1090" alt="image" src="https://github.com/jurgisp/memory-maze/assets/382863/32961305-15d8-4508-bb5f-b8695b4ec80d">

**Comment by jurgisp** [comment]
It would be surely interesting to see how it performs on memory_maze. Closing this issue, however, since it's not in scope for this repo.
