### ISSUE TITLE
WARNING:absl:Cannot set velocity on Entity with no free joint.

### ISSUE THREAD

**Issue by NM512** [jurgisp/dmc-memory-maze#20]
Hi,

Thanks for making nice benchmark task.
I'm curious if there is a way to avoid following warning output once a episode. Am I wrong to use?
This warning seems to appear on other people's [terminal](https://github.com/jurgisp/memory-maze/issues/11#issuecomment-1382225637) as well.

```
WARNING:absl:Cannot set velocity on Entity with no free joint.
```

I'm using [this repo](https://github.com/NM512/dreamerv3-torch) and following command with python3.8.

```
python3 dreamer.py --configs MemoryMaze --logdir ./logdir/test
```

Thanks in advance!

Best regards,
NM512

**Comment by jurgisp** [comment]
I'm getting this warning too, unfortunately, couldn't get rid of it without changing dm_control lib.

**Comment by NM512** [comment]
Ok, I got it. 
Thanks for your really quick reply!
