### ISSUE TITLE
Versionning issues

### ISSUE THREAD

**Issue by my-name-is-D** [jurgisp/dmc-memory-maze#30]
Hello there, this is a possible issue and a solution.

When installing dm_control,  there are no version specified in the setup and the dm_control newest version seems not to be adapted + it may also install the newest mujoco if you donj't already have it. However, memory_maze requires methods that do not exist past mujoco 2.3.7. 

Therefore if you have any versioning issues try:
dm-control-1.0.11 
mujoco-2.3.7 
pyopengl-3.1.7

Took me a bit of searching to have everything working, so if I can save you the trouble.

Dear creators, great job for this amazing work :)
Please do not hesitate to specify the version used in your works.

Best!

**Comment by jurgisp** [comment]
Thanks for the note! We haven't pinned the versions, because we intend the package to be working with latest versions. If it does not, we should fix it. But I just tested it with latest

dm-control               1.0.16
mujoco                   3.1.2

and it seems to be fine. What error were you seeing?

**Comment by my-name-is-D** [comment]
Dear jurgisp,

My apologies if I did a mistake while installing (pip install -e . With python 3.9.7)

I can't recuperate the exact terminal prompts, but I had errors linked to openGL that were not mentioned in the troubleshooting, once this solved i had issues with dm_control not finding mujoco methods in the assigned paths due to version incompatibilities.

Maybe a few requirements were already satisfied before installing memory_maze and I didn't realise it. 

Thus maybe the ideal solution would have been to uninstall dependencies and reinstall them freshly.
