### ISSUE TITLE
Drop box Link for offline data has some problems

### ISSUE THREAD

**Issue by junmokane** [jurgisp/dmc-memory-maze#4]
While exploring on Memory-maze github page, I noticed that offline data (~100GB) dropbox link has some problems. I was trying to download the offline data, but it suddenly stops downloading at some point which was random. I tried this multiple times, but it stopped randomly every time I tried. I also checked on my colleagues' laptop and thought that there may be some collapse in uploaded data.

Would you check the dropbox file one more time?

**Comment by jurgisp** [comment]
That's odd. I've tried downloading the `memmaze9x9/train-part0.zip` file now and succeeded. Which exact file are you downloading?

Since it's Dropbox, there's little I can do, I assume it should just work. Please let me know if it still doesn't, I might try some other method of sharing data.

**Comment by junmokane** [comment]
It worked for `memmaze9x9/train-part0.zip`. I guess there was some internet problem. Thanks!

By the way, the dropbox link seems not working currently.

**Comment by jurgisp** [comment]
I discovered Dropbox does have download bandwidth limits, which may also be a reason for link not working anymore. Working on alternative solution.

I'm curious, did you manage to download the full dataset, or just one part?

**Comment by junmokane** [comment]
Just the file that I mentioned above. Thanks for woking on alternative solution!

**Comment by jurgisp** [comment]
Please try downloading from the new link on [google drive](https://drive.google.com/drive/folders/1RcnkTZVwEHnAQeEuw7X8Y1RPSmrFLDFB). According to their documentation, GDrive has higher bandwidth limits than Dropbox, so hopefully, it will be more stable.

**Comment by junmokane** [comment]
It's working well! Thanks!!!
