### ISSUE TITLE
Is the Id of the Maze Env changed?

### ISSUE THREAD

**Issue by hydro-man** [jurgisp/dmc-memory-maze#5]
Hello!
I found that this project has updated a few days ago.
Is the id to make the env changed? 
I remember the old name is 'dmc_memory_maze:MemoryMaze-9x9-v0', but now it seems not.
I wander to know the differences between the new version and the old one.

**Comment by jurgisp** [comment]
Yes, if you have been using pre-release version (thanks for early interest!), the package was renamed from `dmc_memory_maze` to `memory_maze` for the final v1.0 release. As a result, the gym environment id is now `memory_maze:MemoryMaze-9x9-v0`. That should be the only change.
