### ISSUE TITLE
[Explanations on offline data]

### ISSUE THREAD

**Issue by junmokane** [jurgisp/dmc-memory-maze#6]
Hi, I have question on offline data specification.

When I loaded the one of npz file, I noticed that all the keys like 'action' or 'reward' or 'terminal' have size of 1001. 

Did you just put dummy 'action', 'reward', 'terminal' for the first element? 

I mean if the original sequence is O_0, a_0, r_0, t_0, O_1, a_1, r_1, t_1, ... (O: image, a: action, r: reward, t: terminal), is the offline data formed as O_0, a_-1, r_-1, t_-1, O_1, a_0, r_0, t_0, ... (a_-1, r_-1, t_-1 are some dummy values) ? 

Thanks.

**Comment by jurgisp** [comment]
Yes, that is correct. The first entry of action, reward, and terminal are indeed dummy zero values.
