### ISSUE TITLE
How many hours and how many CPUs are needed?

### ISSUE THREAD

**Issue by GoingMyWay** [jurgisp/dmc-memory-maze#8]
Dear authors,

It is a great repo. May I ask how many hours and how many CPUs are needed to run the experiments for each seed?

**Comment by jurgisp** [comment]
Hi! The best place to find those details is in [the paper](https://arxiv.org/abs/2210.13383). This is the paragraph:

> All agents were evaluated after 100 million environment steps of training. For each baseline and task,
we trained five agents with different random seeds and report the average scores. A single Dreamer
training run took 14 days to train using one GPU learner and 8 CPU actors. A single IMPALA
training run took 20 hours to train using one GPU learner and 128 CPU actors.
